### ISSUE TITLE
reload

### ISSUE THREAD

**Issue by lanxiao89** [tomsun28/bootshiro#2]
在更新角色权限时，执行shiroFilterChainManager.reloadFilterChain();
那么新增 或者 删除某用户的角色事，是否也要执行？

**Comment by tomsun28** [comment]
不需要执行，filterChain加载的是资源和角色的关系，对用户关联角色不影响

**Comment by lanxiao89** [comment]
如果新增 或者 删除了用户的角色，应该也要更新shiro中用户的的角色吧  怎么更新呐？
