### ISSUE TITLE
请问网站该怎么登陆，点注册按钮没反应

### ISSUE THREAD

**Issue by ZhiyuSun** [tomsun28/bootshiro#9]
![image](https://user-images.githubusercontent.com/15209904/118927146-f0f68f00-b973-11eb-9b15-461d085ee615.png)

**Comment by tomsun28** [comment]
你好我晚上恢复下环境。

**Comment by tomsun28** [comment]
redis挂了，现在可以了，这个演示环境时shiro版本的，sureness的版本还在重构中哦，欢迎一起贡献
